/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.julian.mora.csv2folder;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author macbook
 */
public class Window extends javax.swing.JFrame {

    private String selectedCSVFilePath;
    private String selectedDestinationFolderPath = "";
    private int currentColumnIndexFolderName = -1;
    private int currentColumnIndexImageLinks = -1;
    private ArrayList<ArrayList<String>> rows;

    /**
     * Creates new form PrincipalJFrame
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldCSVPath = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBoxFolderName = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxImageLinks = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLogs = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButtonProcessStart = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDestinationFolder = new javax.swing.JTextField();
        jButtonSelectDestinationFolder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Archivo .CSV");

        jTextFieldCSVPath.setEditable(false);

        jButton1.setText("Seleccionar archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxFolderName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFolderNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Columna de nombramiento de carpeta");

        jLabel3.setText("Columna de links de imagenes");

        jComboBoxImageLinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxImageLinksActionPerformed(evt);
            }
        });

        jTextAreaLogs.setEditable(false);
        jTextAreaLogs.setColumns(20);
        jTextAreaLogs.setRows(5);
        jTextAreaLogs.setToolTipText("Logs");
        jScrollPane1.setViewportView(jTextAreaLogs);

        jLabel4.setText("Logs");

        jButtonProcessStart.setText("Procesar");
        jButtonProcessStart.setEnabled(false);
        jButtonProcessStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcessStartActionPerformed(evt);
            }
        });

        jLabel5.setText("Directorio destino");

        jTextFieldDestinationFolder.setEditable(false);

        jButtonSelectDestinationFolder.setText("Seleccionar directorio");
        jButtonSelectDestinationFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectDestinationFolderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(jComboBoxFolderName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldCSVPath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jComboBoxImageLinks, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonProcessStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldDestinationFolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelectDestinationFolder)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCSVPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFolderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxImageLinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDestinationFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelectDestinationFolder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonProcessStart, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.setDialogTitle("Seleccionar archivo CSV");
        fileChooser.setMultiSelectionEnabled(false);

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = fileChooser.getSelectedFile();
                System.out.println("Selected file: " + selectedFile.getAbsolutePath());
                this.selectedCSVFilePath = selectedFile.getAbsolutePath();
                this.jTextFieldCSVPath.setText(selectedCSVFilePath);

                rows = CSVUtils.GetCSVContent(selectedCSVFilePath, ";");
                int index = 0;
                for (String column : rows.get(0)) {
                    jComboBoxFolderName.addItem("Columna [" + (index + 1) + "]: " + column);
                    jComboBoxImageLinks.addItem("Columna [" + (index + 1) + "]: " + column);

                    index++;
                }

                jComboBoxFolderName.setSelectedItem(null);
                jComboBoxImageLinks.setSelectedItem(null);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        ValidateForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxFolderNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFolderNameActionPerformed
        this.currentColumnIndexFolderName = jComboBoxFolderName.getSelectedIndex();
        System.out.println("currentColumnIndexFolderName: " + currentColumnIndexFolderName);
        ValidateForm();
    }//GEN-LAST:event_jComboBoxFolderNameActionPerformed

    private void jComboBoxImageLinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxImageLinksActionPerformed
        this.currentColumnIndexImageLinks = jComboBoxImageLinks.getSelectedIndex();
        System.out.println("currentColumnIndexImageLinks: " + currentColumnIndexImageLinks);
        ValidateForm();
    }//GEN-LAST:event_jComboBoxImageLinksActionPerformed

    private void jButtonProcessStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcessStartActionPerformed
        for (ArrayList<String> row : rows) {
            final String column = row.get(currentColumnIndexFolderName);
            final File dir = new File(selectedDestinationFolderPath, column);
            boolean resultFolderOperation = MkDir.CreateDirectory(dir.getAbsolutePath());

            if (resultFolderOperation) {
                AddTextToLog("Carpeta creada: " + dir.getAbsolutePath());
            } else {
                AddTextToLog("[WARN] Parece que la carpeta ya existe: " + dir.getAbsolutePath());
            }
        }

        JOptionPane.showMessageDialog(null, "Carpetas creadas correctamente!");

        AddTextToLog("Descargando imagenes.");

        for (ArrayList<String> row : rows) {
            final String column = row.get(currentColumnIndexFolderName);
            final String columnImages = row.get(currentColumnIndexImageLinks);
            final File dir = new File(selectedDestinationFolderPath, column);

            DriveImages.DonwloadDriveImage(columnImages, dir.getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonProcessStartActionPerformed

    private void jButtonSelectDestinationFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectDestinationFolderActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.setDialogTitle("Seleccionar destino");
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            selectedDestinationFolderPath = selectedFile.getAbsolutePath();
            jTextFieldDestinationFolder.setText(selectedDestinationFolderPath);
            ValidateForm();
        }
    }//GEN-LAST:event_jButtonSelectDestinationFolderActionPerformed

    private void AddTextToLog(String newLine) {
        SwingUtilities.invokeLater(() -> {
            jTextAreaLogs.append("\n" + newLine);
        });
    }

    private void ValidateForm() {
        jButtonProcessStart.setEnabled(currentColumnIndexFolderName >= 0 && currentColumnIndexImageLinks >= 0 && !selectedDestinationFolderPath.isEmpty());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonProcessStart;
    private javax.swing.JButton jButtonSelectDestinationFolder;
    private javax.swing.JComboBox<String> jComboBoxFolderName;
    private javax.swing.JComboBox<String> jComboBoxImageLinks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaLogs;
    private javax.swing.JTextField jTextFieldCSVPath;
    private javax.swing.JTextField jTextFieldDestinationFolder;
    // End of variables declaration//GEN-END:variables
}
